-- ==============================================================================
-- METAS DE GASTO (límite por categoría) + TRANSACCIONES RECURRENTES
-- Ejecutar este script en el SQL Editor de Supabase.
-- ==============================================================================

-- 1. METAS DE GASTO ------------------------------------------------------------
-- Límite mensual de gasto por categoría. Una meta por categoría por usuario.
CREATE TABLE IF NOT EXISTS budget_goals (
  id bigint generated by default as identity primary key,
  category_id bigint not null references categories (id) on delete cascade,
  amount numeric not null check (amount > 0),
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (category_id, user_id)
);

ALTER TABLE budget_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "budget_goals_select_own" ON budget_goals
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "budget_goals_insert_own" ON budget_goals
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "budget_goals_update_own" ON budget_goals
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "budget_goals_delete_own" ON budget_goals
  FOR DELETE USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS budget_goals_user_id_idx ON budget_goals (user_id);

-- 2. TRANSACCIONES RECURRENTES -------------------------------------------------
-- Plantilla que genera transacciones reales de forma automática según su frecuencia.
CREATE TABLE IF NOT EXISTS recurring_transactions (
  id bigint generated by default as identity primary key,
  amount numeric not null check (amount > 0),
  description text not null default '',
  category_id bigint not null references categories (id) on delete cascade,
  account_id bigint references accounts (id) on delete set null,
  frequency text not null check (frequency in ('weekly', 'monthly', 'yearly')),
  start_date date not null,
  next_run_date date not null,
  last_generated_at timestamptz,
  active boolean not null default true,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

ALTER TABLE recurring_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "recurring_transactions_select_own" ON recurring_transactions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "recurring_transactions_insert_own" ON recurring_transactions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "recurring_transactions_update_own" ON recurring_transactions
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "recurring_transactions_delete_own" ON recurring_transactions
  FOR DELETE USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS recurring_transactions_user_id_idx ON recurring_transactions (user_id);
CREATE INDEX IF NOT EXISTS recurring_transactions_next_run_idx ON recurring_transactions (next_run_date) WHERE active;
